import Car from "../classes/Car";
import Direction from "../enums/Direction";
import Door from "../enums/Door";

export default function pickUpPassenger(car: Car) {
  console.log(car);
  console.log('-------------------------------------------');
  car.openTheDoor(Door["DIANTEIRA ESQUERDA"]);
  car.closeTheDoor(Door["DIANTEIRA ESQUERDA"]);
  car.turnOn();
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.ESQUERDA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.DIREITA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.DIREITA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.honk();
  car.openTheDoor(Door["TRASEIRA DIREITA"]);
  car.closeTheDoor(Door["TRASEIRA DIREITA"]);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.DIREITA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.ESQUERDA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.turn(Direction.DIREITA);
  car.speedUp();
  car.speedDown();
  car.stop();
  car.openTheDoor(Door["TRASEIRA DIREITA"]);
  car.closeTheDoor(Door["TRASEIRA DIREITA"]);
  car.speedUp();
  console.log('...');
  car.turnOff();
}
